version: '3.8'

services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./db/dev.db
    volumes:
      - backend_data:/app/db   # persist database
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "80:80"
    environment:
      - VITE_API_URL=/api
    depends_on:
      - backend
    restart: always

volumes:
  backend_data:
